### ISSUE TITLE
本リポジトリのOSSライセンスについて

### ISSUE THREAD

**Issue by atinfinity** [keisuke-0114/amcl#1]
本リポジトリのOSSライセンスについて確認させてください。  
https://github.com/ros-planning/navigation/blob/melodic-devel/amcl/package.xml#L24 を読むとわかるように元になっているamclパッケージはLGPLです。一方で[本リポジトリのREADME.md](https://github.com/keisuke-0114/amcl/blob/master/README.md)を読むとMITライセンスとなっています。本リポジトリはどのような主張でMITライセンスになっているのでしょうか？

**Comment by airkei** [comment]
> 本リポジトリのOSSライセンスについて確認させてください。
> https://github.com/ros-planning/navigation/blob/melodic-devel/amcl/package.xml#L24 を読むとわかるように元になっているamclパッケージはLGPLです。一方で[本リポジトリのREADME.md](https://github.com/keisuke-0114/amcl/blob/master/README.md)を読むとMITライセンスとなっています。本リポジトリはどのような主張でMITライセンスになっているのでしょうか？

お手数をおかけします、誤記です。README.md を修正致しました。
ご指摘の通り元のamclパッケージからの流用となり、ライセンスはLGPLとなります。

**Comment by atinfinity** [comment]
コメントありがとうございました。
